version: '3.8'

services:
  web:
    build: ./bugtracker
    env_file:
      - ./.env/.dev
    environment:
      - ENV_TYPE=dev
    command: python manage.py runserver 0.0.0.0:8000
    ports:
    - 8000:8000