apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: bugtracker
spec:
  selector:
    app: nginx-deployment
  type: ClusterIP
  ports:
  - name: nginx-service
    protocol: TCP
    port: 1337
    targetPort: 1337