apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: bugtracker
spec:
  selector:
    app: postgres-deployment
  type: ClusterIP
  ports:
  - name: postgres-service
    protocol: TCP
    port: 5432
    targetPort: 5432
    