apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: default
spec:
  selector:
    app: django-web-deployment
  type: NodePort
  ports:
  - name: django-service
    protocol: TCP
    port: 8001
    targetPort: 8001