apiVersion: apps/v1
kind: Deployment
metadata:
  name:  django-web-deployment
  namespace: default
  labels:
    app:  django-web-deployment
spec:
  selector:
    matchLabels:
      app: django-web-deployment
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  django-web-deployment
    spec:
      initContainers:
        - name: init-django
          image: ghcr.io/matei8787/reddit_devops-web:latest
          command: 
            - /bin/sh
            - -c
            - |
              python manage.py migrate --noinput && \
              python manage.py collectstatic --noinput --clear
          envFrom:
            - configMapRef:
                name: bugtracker-configmap
            - secretRef:
                name: bugtracker-secret
          volumeMounts:
            - name:  static-files
              mountPath:  /home/app/web/staticfiles
      containers:
      - name:  django
        image:  ghcr.io/matei8787/reddit_devops-web:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        command: 
          - /bin/sh
          - -c
          - gunicorn bugtracker.wsgi:application --bind 0.0.0.0:8001
        envFrom:
        - configMapRef:
            name: bugtracker-configmap
        - secretRef:
            name: bugtracker-secret
        ports:
        - containerPort:  8001
          name:  http
        volumeMounts:
        - name: static-files
          mountPath: /home/app/web/staticfiles
      restartPolicy: Always
      volumes:
        - name:  static-files
          persistentVolumeClaim:
            claimName: static-files-pvc