apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx-deployment
  namespace: default
  labels:
    app:  nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-deployment
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  nginx-deployment
    spec:
      containers:
      - name:  nginx-deployment
        image:  ghcr.io/matei8787/reddit-devops-nginx:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        envFrom:
        - configMapRef:
            name: bugtracker-configmap
        - secretRef:
            name: bugtracker-secret
        ports:
        - containerPort:  1337
          name:  http
        volumeMounts:
        - name: static-files
          mountPath: /home/app/web/staticfiles
      volumes:
        - name: static-files
          persistentVolumeClaim:
            claimName: static-files-pvc