apiVersion: apps/v1
kind: Deployment
metadata:
  name:  postgres-deployment
  namespace: default
  labels:
    app:  postgres-deployment
spec:
  selector:
    matchLabels:
      app: postgres-deployment
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  postgres-deployment
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  postgres-deployment
        image: postgres:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        envFrom:
          - configMapRef:
              name: bugtracker-configmap
          - secretRef:
              name: bugtracker-secret
        ports:
        - containerPort:  5432
          name:  postgres
        volumeMounts:
          - name:  postgres-files
            mountPath:  /var/postgres/data
      volumes:
        - name: postgres-files
          persistentVolumeClaim:
            claimName: postgres-data-pvc