apiVersion: v1
kind: Secret
metadata:
  name: bugtracker-secret
  namespace: bugtracker
type: Opaque
stringData:
  # Example:
  # password: {{ .Values.password | b64enc }}
  SECRET_KEY: o_&#!wu4+6hj3b$yyzu^s1yugxd723on1(!eahm*0revnmn5jv
  DB_NAME: bugtracker
  DB_USER: dorb
  DB_PASS: dorb
  DB_HOST: postgres-service
  DB_PORT: "5432"
  POSTGRES_DB: bugtracker
  POSTGRES_USER: dorb
  POSTGRES_PASSWORD: dorb

